services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    networks:
      - laravel

  nginx:
    build:
      context: ./docker/nginx   # 👈 IMPORTANT
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
